clustering:
  algorithm: GMMClustering
  n_init: 3
  reduced_dimension: 32
  early_stopping:
    max_cluster_tokens: 1024
    max_cluster_size: 5
  embedding:
    model: Alibaba-NLP/gte-large-en-v1.5
    dims: 1024
    # model: Alibaba-NLP/gte-base-en-v1.5
    # dims: 768

retrieval:
  model: Alibaba-NLP/gte-large-en-v1.5
  dims: 1024

reranking:
  model: avsolatorio/GIST-large-Embedding-v0

tree_builder:
  leaf_text_tokens: 256
  parent_text_tokens: 1024
  max_layers: 3

neo4j:
  uri:
  user:
  password:

llm:
  endpoint:
  key:
  model_id:
